/**
 * Every UI string in one place, so wording and language can be changed consistently.
 *
 * Danish labels come from the wireframes. The English stage and button names come from the spec
 * and are kept as-is until the UI language is decided (CLAUDE.md, open question 7).
 */
export const t = {
  brand: "Frank's Poolhouse",
  nav: {
    tournaments: 'Turneringer',
    players: 'Spillere',
    season: 'Sæson',
    newTournament: 'Ny Turnering',
    login: 'Log ind',
    logout: 'Logout',
  },
  frontpage: {
    title: "Frank's Poolhouse turnerings platform",
    leaderboard: 'Sæson Leaderboard',
  },
  tournaments: {
    title: 'Turneringer',
    date: 'Dato',
    winner: 'Vinder',
    participants: 'Antal deltagere',
    format: 'Format',
    none: 'Ingen afsluttede turneringer endnu.',
  },
  detail: {
    inProgress: 'Turneringen er i gang.',
    followLive: 'Følg den live',
    placings: 'Placeringer',
    placement: 'Placering',
    points: 'Point',
    poolWins: 'Vundne puljekampe',
    correctHelp:
      'Klik på et resultat for at rette det; placeringer og point opdateres med det samme. Større ændringer kræver, at turneringen genåbnes.',
    reopen: 'Genåbn turnering',
    confirmReopen:
      'Genåbn turneringen? Den går tilbage til slutspillet, og dens point fjernes, indtil den afsluttes igen.',
    needsReopen:
      'Den rettelse ville ændre, hvem der gik videre eller mødte hinanden senere. Genåbn turneringen for at lave den.',
    otherInProgress: 'Der er en anden turnering i gang. Afslut den først.',
  },
  placements: {
    '1st': '1.',
    '2nd': '2.',
    '3rd': '3.',
    '4th': '4.',
    '5-8': '5.–8.',
    participation: 'Deltager',
  },
  players: {
    title: 'Spillere',
    name: 'Navn',
    baseHandicap: 'Handicap',
    frameHandicap: 'Frame-handicap',
    seasonPoints: 'Sæsonpoint',
    participation: 'Deltagelse',
    wins: 'Wins',
    semifinals: 'Semifinals',
    quarterfinals: 'Quarterfinals',
    member: 'Medlem',
    memberThisSeason: 'Medlem denne sæson',
    none: 'Ingen spillere endnu.',
    edit: 'Rediger',
    delete: 'Slet',
    confirmDelete: (name: string) => `Er du sikker på at du vil slette ${name}?`,
    nameTaken: 'Der findes allerede en spiller med det navn.',
    hasTournaments: 'Spilleren har spillet turneringer og kan ikke slettes.',
  },
  season: {
    title: 'Sæson',
    empty: 'Ingen har spillet i denne sæson endnu.',
  },
  login: {
    title: 'Login',
    username: 'Username',
    password: 'Password',
    submit: 'Log ind',
    cancel: 'Annuller',
    wrongCredentials: 'Forkert brugernavn eller adgangskode',
    tooManyAttempts: 'For mange forsøg. Prøv igen om lidt.',
    failed: 'Login mislykkedes. Prøv igen.',
  },
  logout: {
    confirm: 'Er du sikker på at du vil logge ud?',
    yes: 'Log ud',
    cancel: 'Annuller',
  },
  create: {
    addPlayer: 'Tilføj spiller',
    addNewPlayer: 'Tilføj ny spiller',
    finish: 'Færdiggør',
    cancel: 'Cancel',
    remove: 'Fjern',
    noMatch: 'Ingen spillere fundet',
    count: (n: number) => (n === 1 ? '1 spiller' : `${n} spillere`),
    pools: (sizes: number[]) => `Puljer: ${sizes.join(' + ')}`,
    tooFew: 'Der skal mindst være 4 spillere',
    alreadyRunning: 'Der er allerede en turnering i gang. Afslut eller annuller den først.',
    goToRunning: 'Gå til turneringen',
  },
  stages: {
    pools: 'Preliminary pools',
    quarterfinals: 'Quarterfinals',
    semifinals: 'Semifinals',
    thirdPlace: 'Third place finals',
    final: 'Finals',
  },
  ongoing: {
    finalizeBrackets: 'finalize brackets',
    completeQualifiers: 'complete qualifier brackets',
    concludeTournament: 'conclude tournament',
    upNext: 'Up next',
    week: 'Uge',
    cancelTournament: 'Annuller turnering',
    confirmStart: 'Er puljerne klar? Bagefter kan de ikke ændres.',
    confirmCancel: 'Er du sikker på at du vil annullere turneringen? Den bliver slettet.',
    confirmConclude:
      'Afslut turneringen? Placeringer og point gemmes, og den kommer på listen over turneringer.',
  },
  pools: {
    pool: 'Pulje',
    dragHelp:
      'Træk en spiller over på en anden for at bytte dem, eller ind i en anden pulje for at flytte spilleren.',
    tooSmall: 'En pulje skal have mindst 2 spillere.',
    setScore: 'Set score',
    won: 'Vundne',
    tied: 'Står lige. Admin vælger rækkefølgen, når kvalifikationen afgøres.',
    sittingOut: 'Sidder over',
    complete: 'Alle kampe i puljen er spillet.',
    allComplete: 'Alle puljekampe er spillet. Næste trin er complete qualifier brackets.',
  },
  score: {
    raceTo: (n: number) => `Race to ${n}`,
    clear: 'Ryd resultat',
  },
  qualify: {
    knockout: 'Slutspil',
    quarterfinals: 'Quarterfinals (8)',
    semifinals: 'Semifinals (4)',
    raceTo: 'Race to',
    cannot: 'Der er ikke spillere nok til det valgte slutspil.',
    qualifiers: (n: number) => `Disse ${n} går videre:`,
    tie: (players: string) => `Står lige: ${players}`,
    pickOrder: 'Klik spillerne i rækkefølge, bedste først.',
    startOver: 'Start forfra',
    tiesLeft: 'Der er stadig spillere, der står lige. Vælg rækkefølgen først.',
    confirm: (round: string, raceTo: number) =>
      `Start slutspillet med ${round}, race to ${raceTo}? Puljeresultaterne kan ikke ændres bagefter.`,
  },
  knockout: {
    title: 'Slutspil',
    waiting: 'Venter …',
    laterPlayed:
      'Det ville ændre, hvem der spiller en senere kamp, som allerede har et resultat. Ryd den kamps resultat først.',
    done: 'Finalen og bronzekampen er spillet. Næste trin er conclude tournament.',
  },
  live: {
    drawing: 'Puljerne bliver lavet …',
    noTournament: 'Ingen turnering i gang lige nu',
  },
  yes: 'Ja',
  no: 'Nej',
  save: 'Gem',
  cancel: 'Annuller',
  loading: 'Indlæser…',
  loadFailed: 'Kunne ikke hente data. Prøv igen.',
  saveFailed: 'Kunne ikke gemme. Prøv igen.',
  notFound: 'Siden findes ikke',
  placeholder: 'Kommer snart',
};
